

weixin4j:
  config:
    appid: wxe1670732c6504e02
    secret: 91478f59449c2735d607f94aa08157b8
  pay-config:
    cert-path:
    cert-secret:
    mch-id:
    mch-key:
  openssl-path:
  rsa-pub-key-pkcs1:
  rsa-pub-key-pkcs8:
spring:
  datasource:
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/testdata?useUnicode=true&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&autoReconnect=true&characterEncoding=utf-8
      username: root
      password: root
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      max-evictable-idle-time-millis: 60000
      validation-query: SELECT 1 FROM DUAL
      # validation-query-timeout: 5000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      #filters: #配置多个英文逗号分隔(统计，sql注入，log4j过滤)
      filters: stat,wall,config
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
  thymeleaf:
    cache: false
    suffix: .html
    prefix: classpath:/templates/

###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:/mapping/**/*.xml
  type-aliases-package: com.test.**.entity
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
    logic-delete-value: 1
    logic-not-delete-value: 0
    enable-sql-runner: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
